#!/bin/bash

case "${PHP_VERSION}" in
  "5.6")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=2.5.5
  XDEBUG_PORT="xdebug.remote_port=9003"
  XDEBUG_MODE="xdebug.remote_enable=1"
  XDEBUG_CONNECT="xdebug.remote_connect_back=1"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "7.1")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.1.1
  XDEBUG_PORT="xdebug.remote_port=9003"
  XDEBUG_MODE="xdebug.remote_enable=1"
  XDEBUG_CONNECT="xdebug.remote_connect_back=1"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "7.2")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.1.1
  XDEBUG_PORT="xdebug.remote_port=9003"
  XDEBUG_MODE="xdebug.remote_enable=1"
  XDEBUG_CONNECT="xdebug.remote_connect_back=1"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "7.3")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.1.1
  XDEBUG_PORT="xdebug.remote_port=9003"
  XDEBUG_MODE="xdebug.remote_enable=1"
  XDEBUG_CONNECT="xdebug.remote_connect_back=1"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "7.4")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.1.1
  XDEBUG_PORT="xdebug.remote_port=9003"
  XDEBUG_MODE="xdebug.remote_enable=1"
  XDEBUG_CONNECT="xdebug.discover_client_host=1"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "8.0")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.1.1
  XDEBUG_PORT="xdebug.client_port=9003"
  XDEBUG_MODE="xdebug.mode=develop,debug"
  XDEBUG_CONNECT="xdebug.discover_client_host=true"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "8.1")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.1.6
  XDEBUG_PORT="xdebug.client_port=9003"
  XDEBUG_MODE="xdebug.mode=develop,debug"
  XDEBUG_CONNECT="xdebug.discover_client_host=true"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "8.2")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.2.2
  XDEBUG_PORT="xdebug.client_port=9003"
  XDEBUG_MODE="xdebug.mode=develop,debug"
  XDEBUG_CONNECT="xdebug.discover_client_host=true"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "8.3")
  REDIS_VERSION=5.3.4
  XDEBUG_VERSION=3.3
  XDEBUG_PORT="xdebug.client_port=9003"
  XDEBUG_MODE="xdebug.mode=develop,debug"
  XDEBUG_CONNECT="xdebug.discover_client_host=true"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  "8.4")
  REDIS_VERSION=6.1.0
  XDEBUG_VERSION=3.5
  XDEBUG_PORT="xdebug.client_port=9003"
  XDEBUG_MODE="xdebug.mode=develop,debug"
  XDEBUG_CONNECT="xdebug.discover_client_host=true"
  XDEBUG_CLIENT_HOST="xdebug.client_host=host.docker.internal"
  XDEBUG_START_WITH_REQUEST="xdebug.start_with_request=yes"
  ERROR_REPORTING="error_reporting=E_ALL"
  ;;
  *)
  REDIS_VERSION="UNKNOWN_VERSION_CHECK_BUILD_CFG"
  XDEBUG_VERSION="UNKNOWN_VERSION_CHECK_BUILD_CFG"
  XDEBUG_PORT="UNKNOWN_XDEBUG_PORT"
  XDEBUG_MODE="UNKNOWN_XDEBUG_MODE"
  XDEBUG_CONNECT="UNKNOWN_XDEBUG_CONNECT"
  XDEBUG_CLIENT_HOST="UNKNOWN_XDEBUG_CLIENT_HOST"
  XDEBUG_START_WITH_REQUEST="UNKNOWN_XDEBUG_START_WITH_REQUEST"
  ERROR_REPORTING="UNKNOWN_ERROR_REPORTING"
  ;;
esac
